name: hiringDataScraper
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - beautifulsoup4=4.10.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - et_xmlfile=1.1.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.24
  - libsqlite=3.43.0
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - ncurses=6.4
  - numpy=1.26.0
  - openpyxl=3.1.2
  - openssl=3.1.3
  - pandas=2.1.1
  - pip=23.2.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3.post1
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - soupsieve=2.3.1
  - tk=8.6.13
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.2.6
  - pip:
    - boto3==1.28.54
    - botocore==1.31.54
    - certifi==2023.7.22
    - charset-normalizer==3.2.0
    - idna==3.4
    - jmespath==1.0.1
    - lxml==4.9.3
    - py4j==0.10.9.7
    - pyspark==3.4.1
    - requests==2.31.0
    - s3transfer==0.6.2
    - tqdm==4.66.1
    - ujson==5.8.0
    - urllib3==1.26.16
    - warcio==1.7.4
